### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by lstienba** [CenterForOpenScience/SHARE#544]
Running `python manage.py runserver` encountered the following error message:

``` 
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000021ACEF64C80>
Traceback (most recent call last):
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 226, in
wrapper
    fn(*args, **kwargs)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\management\commands\runserver.
py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 249, in
raise_last_exception
    six.reraise(*_exception)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 226, in
wrapper
    fn(*args, **kwargs)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\log.py", line 69, in configur
e_logging
    logging_config_func = import_string(logging_config)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\module_loading.py", line 20,
in import_string
    module = import_module(module_path)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\lstienba\documents\share_harvester\SHARE\project\log.py", line 4, in <module>
    from django.utils.deprecation import RemovedInDjango110Warning
ImportError: cannot import name 'RemovedInDjango110Warning'```

Running on Windows 10 environment in Powershell.  

When running in Git Bash, the `./up.sh` command also gives the following error message:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\log.py", line 69, in configure_logging
    logging_config_func = import_string(logging_config)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\site-packages\django\utils\module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "C:\Users\lstienba\AppData\Local\Continuum\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\lstienba\documents\share_harvester\SHARE\project\log.py", line 4, in <module>
    from django.utils.deprecation import RemovedInDjango110Warning
ImportError: cannot import name 'RemovedInDjango110Warning'
```

**Comment by leb2dg** [comment]
Hi! What version of Django are you running?
```
(share) LaurenB-MacBook-Air:SHARE laurenbarker$ ./manage.py --version
1.9.7
```

**Comment by lstienba** [comment]
Hi Lauren,

I am running version 1.10.4 of Django.  Thank-you, Lisa

**Comment by leb2dg** [comment]
Ah, this project requires Django 1.9.7 because one of our dependencies has a conflict with Django 1.10. If you downgrade your Django, it should resolve that error. 

I'm going to close this issue but feel free to create another one if you run into something else!
